# Generated by Django 4.2 on 2023-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=50)),
                ('header_social_url_twt', models.URLField()),
                ('header_socila_url_link', models.URLField()),
                ('header_social_url_fb', models.URLField()),
                ('header_social_url_insta', models.URLField()),
                ('header_social_url_yt', models.URLField()),
                ('header_contact', models.CharField(max_length=12)),
                ('header_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
