# Generated by Django 4.2 on 2023-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='popularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_imageone', models.FileField(default=None, max_length=250, upload_to='popularcourse/')),
                ('course_title', models.CharField(max_length=50)),
                ('course_flag', models.CharField(max_length=50)),
                ('course_imagetwo', models.CharField(max_length=50)),
            ],
        ),
    ]
