# Generated by Django 4.2 on 2023-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularcourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcourse',
            name='course_imagetwo',
            field=models.FileField(default=None, max_length=250, upload_to='popularcourse/'),
        ),
    ]
