# Generated by Django 4.2 on 2023-06-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificaterequest', '0003_choosecenter_alter_certificaterequest_center'),
        ('postcategories', '0004_alter_postcategories_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJoined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('facultyname', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
                ('coursestartdate', models.DateTimeField()),
                ('courseenddate', models.DateTimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaterequest.choosecenter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcategories.postcategories')),
            ],
        ),
    ]
