# Generated by Django 4.2 on 2023-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentjoined',
            name='courseenddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentjoined',
            name='coursestartdate',
            field=models.DateField(),
        ),
    ]
