# Generated by Django 4.2 on 2023-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentjoined_courseenddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjoined',
            name='sign_auth',
            field=models.FileField(max_length=250, null=True, upload_to='signingauth/'),
        ),
    ]
