# Generated by Django 4.2 on 2023-06-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentjoined_sign_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentjoined',
            name='sign_auth',
            field=models.FileField(blank=True, max_length=250, upload_to='signingauth/'),
        ),
    ]
