# Generated by Django 4.2 on 2023-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_image', models.FileField(default=None, upload_to='student/')),
                ('student_desc', models.TextField(max_length=150)),
            ],
        ),
    ]
