# Generated by Django 4.2 on 2023-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategories',
            name='category_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
