# Generated by Django 4.2 on 2023-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcategories', '0002_alter_postcategories_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategories',
            name='category_title',
            field=models.CharField(max_length=255),
        ),
    ]
