# Generated by Django 4.2 on 2023-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=12)),
                ('phone2', models.CharField(max_length=12)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('offaddress', models.TextField()),
                ('googlemap', models.CharField(max_length=250)),
                ('contactinfo', models.TextField()),
            ],
        ),
    ]
