# Generated by Django 4.2 on 2023-06-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='phone1',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='phone2',
            field=models.CharField(max_length=14),
        ),
    ]
