# Generated by Django 4.2 on 2023-06-08 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0002_alter_contactdata_phone1_alter_contactdata_phone2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='googlemap',
            new_name='googlemap1',
        ),
        migrations.AddField(
            model_name='contactdata',
            name='googlemap2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
