# Generated by Django 4.2 on 2023-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opendays', models.CharField(max_length=50)),
                ('specificdayopen', models.CharField(max_length=50)),
                ('closeday', models.CharField(max_length=50)),
            ],
        ),
    ]
