# Generated by Django 4.2 on 2023-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_branch', models.CharField(max_length=50)),
                ('course_date', models.DateField()),
                ('course_time', models.TimeField()),
            ],
        ),
    ]
