# Generated by Django 4.2 on 2023-08-18 06:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_detail',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
