# Generated by Django 4.2 on 2023-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('center', models.CharField(choices=[('noidasec16', 'NOIDA SEC 16'), ('ghaziabad', 'GHAZIABAD'), ('noidasec63', 'NOIDA SEC 63'), ('gurugram', 'GURUGRAM')], default='noidasec16', max_length=100)),
            ],
        ),
    ]
