# Generated by Django 4.2 on 2023-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaterequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='facultyname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='phoneno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='studentid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
