# Generated by Django 4.2 on 2023-06-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificaterequest', '0002_certificaterequest_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centername', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaterequest.choosecenter'),
        ),
    ]
