# Generated by Django 4.2 on 2023-06-23 10:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('headerservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, upload_to='services/')),
                ('description_one', tinymce.models.HTMLField()),
                ('heading_two', models.CharField(max_length=250)),
                ('description_two', tinymce.models.HTMLField()),
                ('heading_three', models.CharField(max_length=250)),
                ('description_three', tinymce.models.HTMLField()),
                ('heading_four', models.CharField(max_length=250)),
                ('description_four', tinymce.models.HTMLField()),
                ('heading_five', models.CharField(max_length=250)),
                ('description_five', tinymce.models.HTMLField()),
                ('heading_six', models.CharField(max_length=250)),
                ('description_six', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, upload_to='services/')),
                ('description_one', tinymce.models.HTMLField()),
                ('heading_two', models.CharField(max_length=250)),
                ('description_two', tinymce.models.HTMLField()),
                ('heading_three', models.CharField(max_length=250)),
                ('description_three', tinymce.models.HTMLField()),
                ('heading_four', models.CharField(max_length=250)),
                ('description_four', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='CorporateTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, upload_to='services/')),
                ('description_one', tinymce.models.HTMLField()),
                ('heading_two', models.CharField(max_length=250)),
                ('description_two', tinymce.models.HTMLField()),
                ('heading_three', models.CharField(max_length=250)),
                ('description_three', tinymce.models.HTMLField()),
                ('heading_four', models.CharField(max_length=250)),
                ('description_four', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, upload_to='services/')),
                ('description_one', tinymce.models.HTMLField()),
                ('heading_two', models.CharField(max_length=250)),
                ('description_two', tinymce.models.HTMLField()),
                ('heading_three', models.CharField(max_length=250)),
                ('description_three', tinymce.models.HTMLField()),
                ('heading_four', models.CharField(max_length=250)),
                ('description_four', tinymce.models.HTMLField()),
                ('heading_five', models.CharField(max_length=250)),
                ('description_five', tinymce.models.HTMLField()),
            ],
        ),
    ]
