# Generated by Django 4.2 on 2023-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourclients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourclients',
            name='client_image',
            field=models.FileField(default=None, upload_to='clients/'),
        ),
    ]
